apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d6ehfgqkt-python 
  janus-idp.io/tekton: d6ehfgqkt-python
  backstage.io/kubernetes-id: d6ehfgqkt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d6ehfgqkt-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml